default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 25
  username: postgres
  password: postgres

development:
  <<: *default
  database: magazine_development

test:
  <<: *default
  database: magazine_test

production:
  <<: *default
  database: 
  username: 
  password: <%= ENV['MAGAZINE_DATABASE_PASSWORD'] %>
